### ISSUE TITLE
Missing Files

### ISSUE THREAD

**Issue by EpicScorpion524** [Sappytron/HorizonPlus#1]
I cant find any of the .simhubdash in the files i extracted from the .zip folder.

**Comment by YoYoGavri** [comment]
> I cant find any of the .simhubdash in the files i extracted from the .zip folder.

Make sure to go to the releases tab, and get the most recent version. After unzipping the folder, all the .simhudash files will be there. Make sure to click on all of them and install them.

**Comment by EpicScorpion524** [comment]
Thank you i was able to find them now.

**Comment by EpicScorpion524** [comment]
Thank you i was able to find them now
